version: '2'

volumes:
  app_data:
  redis_data:

services:
  app:
    image: oficina:aula3-network
    container_name: aula-3
    environment:
     - REDIS_URL=redis
    build: .
    volumes:
      - app_data:/tmp
    ports:
      - 5000:5000
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
